### ISSUE TITLE
发现bug，恶心

### ISSUE THREAD

**Issue by liuhuan139** [S-mohan/smusic#6]
playByMode(type, callback, isInit)
这个方法里面，在列表播放的时候，居然出现如下错误：
第1首的下一首变成11，第2首的下一首变成21.。。。。
所以，你也知道是什么错了。这个好改。。。

现在我碰到的另外一个恶心问题，就是在列表播放mode下，播放完一首，概率出现不自动播放下一首的情况。

**Comment by 1844593262** [comment]
bug 多久调啊，用了不要说别人的东西恶心
